name: CI'

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  ci:
    name: "Lint, Build and Test"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Caching for faster builds
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: |
          npm i

      - name: Test code
        run: |
          npm run test

      - name: Print Coverage report
        run: |
          npm run coverage
